//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin.Web.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MenuItem()
        {
            this.MenuItems1 = new HashSet<MenuItem>();
        }
    
        public int Id { get; set; }
        public System.DateTime AddedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Caption { get; set; }
        public string Route { get; set; }
        public bool HasChildren { get; set; }
        public string ClassName { get; set; }
        public string IconName { get; set; }
        public bool IsVisible { get; set; }
        public int SortOrder { get; set; }
        public int MenuGroupId { get; set; }
        public Nullable<int> ParentId { get; set; }
    
        public virtual MenuGroup MenuGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuItem> MenuItems1 { get; set; }
        public virtual MenuItem MenuItem1 { get; set; }
    }
}
